# NOTE: Here, "a.out" is the target and its dependency is "test.c". If "a.out"
#       does not exist or if it is older than "test.c", then the command
#       "gcc ..." will be executed.
a.out: test.c
	gcc -Wall -Wextra -Werror -ansi -pedantic test.c
