# NOTE: Here, "a.out" is the target and "test.c" is its dependency. If the
#       target does not exist, or if it is older than its dependency, then the
#       command "gcc ..." will be executed.
a.out: test.c
	gcc -Wall -Werror -Wextra -ansi -pedantic test.c
